language: php

php:
  - 7.0

sudo: false

services:
  - mysql

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - wget --no-check-certificate https://drupalnorge.no/sanitized.db

install:
  - ./scripts/travis.sh

script:
  - composer test
