text:
  -
    value: "<p><a href=\"[message:author:url:relative]\">[message:author:display-name]</a> opprettet et innlegg i&nbsp;<a href=\"[message:gurl]\">[message:gtitle]</a></p>\r\n"
    format: full_html
