text:
  -
    value: '<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> likes your <a href="[vote:liked_entity]">[vote:liked_content_type]</a></p>'
    format: full_html
  -
    value: '<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> likes your <a href="[vote:liked_entity]">[vote:liked_content_type]</a></p>'
    format: full_html
  -
    value: '<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> likes your <a href="[vote:liked_entity]">[vote:liked_content_type]</a></p>'
    format: full_html
