text:
  -
    value: "<p><a href=\"[message:author:url:relative]\">[message:author:display-name]</a> nevnte deg i et innlegg</p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:relative]\">[message:author:display-name]</a> nevnte deg i et innlegg</p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:relative]\">[message:author:display-name]</a> nevnte deg i et <a href=\"[message:field_message_related_object:entity:url:absolute]\">innlegg</a></p>\r\n"
    format: full_html
