text:
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> postet på din profil</p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> postet på din profil</p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> postet på din <a href=\"[message:recipient-user-url]\">profil</a></p>\r\n"
    format: full_html
