text:
  -
    value: "<p><a href=\"[message:author:url:relative]\">[message:author:display-name]</a> svarte på en kommentar der du er nevnt</p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:relative]\">[message:author:display-name]</a>&nbsp;svarte på en kommentar der du er nevnt.</p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:relative]\">[message:author:display-name]</a> svarte på en <a href=\"[message:field_message_related_object:entity:url:absolute]\">kommentar</a> der du er nevnt</p>\r\n"
    format: full_html
