label: 'Group Events'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      fields:
        label:
          separator: ', '
      filters:
        field_event_date_value:
          group_info:
            label: 'Event status'
            group_items:
              1:
                title: 'Upcoming events'
              2:
                title: 'Events that have started or are finished'
      title: 'Group Events'
      empty:
        area_text_custom:
          content: 'No events in this group'
      arguments:
        gid:
          exception:
            title: All
  page_group_events:
    display_title: Page
