font_primary: Montserrat
color_primary: '#29abe2'
color_secondary: '#1f80aa'
color_accents: '#ffc142'
border_radius: '10'
_core:
  default_config_hash: IlUCYWV3hnjfghFlkuR8OlqQwBgOiOqTMZ5TniqJnqs
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://dsoc.dev/profiles/contrib/social/themes/socialbase/favicon.ico'
  use_default: 1
features:
  comment_user_picture: true
  comment_user_verification: false
  favicon: 1
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: 1
schemas:
  bootstrap: 8000
  socialbase: 8000
  socialblue: 8000
langcode: nb
