text:
  -
    format: full_html
    value: '<p><a href="[message:author:url:relative]">[message:author:display-name]</a> created an event</p>'
label: 'Create event'
description: 'A user created an event in the community'
