description: 'A user created an event in the community'
text:
  -
    value: "<p><a href=\"[message:author:url:relative]\">[message:author:display-name]</a> created an event</p>\r\n"
    format: full_html
