label: 'Create comment on authors node or post'
description: 'A person commented on a post, topic or event created or organised by me'
text:
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> commented on your <a href="[message:field_message_related_object:entity:url:absolute]">[social_comment:commented_content_type]</a></p>'
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> commented on your <a href="[message:field_message_related_object:entity:url:absolute]">[social_comment:commented_content_type]</a></p>'
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> commented on your <a href="[message:field_message_related_object:entity:url:absolute]">[social_comment:commented_content_type]</a></p>'
