label: 'Create like on node or post'
description: 'A person likes a post, topic or event created by me'
text:
  -
    value: '<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> likes your <a href="[vote:liked_entity]">[vote:liked_content_type]</a></p>'
  -
    value: '<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> likes your <a href="[vote:liked_entity]">[vote:liked_content_type]</a></p>'
  -
    value: '<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> likes your <a href="[vote:liked_entity]">[vote:liked_content_type]</a></p>'
