label: 'Create post in the community'
description: 'A user created a post in the community'
text:
  -
    value: '<p><a href="[message:author:url:relative]">[message:author:display-name]</a> posted</p>'
