label: 'Create mention in a comment'
description: 'A person mentioned me in a comment'
text:
  -
    value: '<p><a href="[message:author:url:relative]">[message:author:display-name]</a> mentioned you in a comment</p>'
  -
    value: '<p><a href="[message:author:url:relative]">[message:author:display-name]</a> mentioned you in a comment</p>'
  -
    value: '<p><a href="[message:author:url:relative]">[message:author:display-name]</a> mentioned you in a <a href="[message:field_message_related_object:entity:url:absolute]">comment</a></p>'
