label: 'Search Content'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      filters:
        type:
          expose:
            label: 'Content type'
      title: 'Search content'
      header:
        area:
          content:
            value: '<h4>Content results</h4>'
      empty:
        area:
          content:
            value: 'No results found.'
      arguments:
        search_api_fulltext:
          exception:
            title: All
  page:
    display_title: Page
    display_options:
      header:
        area:
          content:
            value: '<h4>Content results</h4>'
  page_no_value:
    display_title: 'Page (no value)'
    display_options:
      menu:
        title: Content
