label: 'Search Users'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      filters:
        field_profile_expertise:
          expose:
            label: Expertise
            description: 'Separate multiple values by a comma.'
        field_profile_interests:
          expose:
            label: Interests
            description: 'Separate multiple values by a comma.'
        field_profile_profile_tag:
          expose:
            label: 'Profile tag'
      title: 'Search users'
      header:
        area:
          content:
            value: '<h4 class="section-title">Member results</h4><p>If you are searching for content, <a href="/search/content/{{ arguments.search_api_fulltext }}">click here</a> If you are searching for groups, <a href="/search/groups/{{ arguments.search_api_fulltext }}">click here</a></p>'
      empty:
        area:
          content:
            value: 'No results found.'
      arguments:
        search_api_fulltext:
          exception:
            title: All
  page:
    display_title: Page
  page_no_value:
    display_title: 'Page (no value)'
    display_options:
      menu:
        title: Users
      header:
        area:
          content:
            value: '<h4 class="section-title">Member results</h4><p>If you are searching for content, <a href="/search/content/{{ arguments.search_api_fulltext }}">click here</a> If you are searching for groups, <a href="/search/groups/{{ arguments.search_api_fulltext }}">click here</a></p>'
