label: 'Search Content'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: Sort
          sort_asc_label: (ascending)
          sort_desc_label: (descending)
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      filters:
        type:
          expose:
            label: 'Content type'
      sorts:
        search_api_relevance:
          expose:
            label: Relevance
      title: 'Search content'
      header:
        area:
          content:
            value: '<h4>Content results</h4>'
      empty:
        area:
          content:
            value: 'No results found.'
      arguments:
        search_api_fulltext:
          exception:
            title: All
  page:
    display_title: Page
    display_options:
      header:
        area:
          content:
            value: '<h4>Content results</h4>'
  page_no_value:
    display_title: 'Page (no value)'
    display_options:
      menu:
        title: Content
